### ISSUE TITLE
与诸神字幕组合作加入更多的资源

### ISSUE THREAD

**Issue by mzhboy** [zogvm/zogvm#1]
发现软件自带的资源很有限，希望可以加入更多资源。比如TBS电视台的 [《世界遗产》](http://i.kamigami.org/?s=%E4%B8%96%E7%95%8C%E9%81%97%E4%BA%A7) 系列

**Comment by zogvm** [comment]
http://i.kamigami.org/category/documentary
 这个俺都有。但是呢。。因为发布的都是网盘，差不多1,2年就因为各种原因失效了。所以不好留存。
收录一般是ED2K 或者 磁力链接 为主，其地址不依赖于任何网站，而是P2P的进行。
扩展库定期更新，目的是为了防止各网站被封而保存地址的。
平时浏览建议去各网站，怕广告多或者想批量下些片可以用扩展库。

**Comment by mzhboy** [comment]
有没有爬 [动漫花园](https://share.dmhy.org/) ，上面世界遗产的磁力链接，以及其他的一些ACG相关的资源

**Comment by zogvm** [comment]
谢谢。这个可以有。下个版本加入。

**Comment by zogvm** [comment]
网盘地址内已有1.17版。加入该资源。（GITHUB次日上传）
由于程序运载能力有限。只显示磁力地址长度小于1024字节。所以展示花园的资源只有14W。
其中有9W多未进行展示但已收录在DB内。可以用SQLITESPY去看。

**Comment by mzhboy** [comment]
花园的链接可以优化一下。花园的磁力链接带tracker信息(tr=xxx 字段)，而事实上磁力只需要hash值就行。这样的话，去掉tracker信息，只保留hash可以减少不少容量；然后tracker信息可以另外用张表扔进去，甚至连 `magnet:?xt=urn:btih:` 这样的字符串都可以省略，复制的时候再添加就好。
另外磁力的 dn=xxx 也可以取消，那个是种子名字，另起一列看起来会更简洁，也可以用来查找同名的种子
